import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/Favicon.png"
          type="image/<generated>"
          sizes="<generated>"
        />
        <title>Nutrition Rule</title>
      </head>

      <body style={{margin: 0}} className={inter.className}>{children}</body>
    </html>
  )
}
